[build]
  publish = "frontend/dist"
  functions = "netlify/functions"
  # Functions တွေအတွက် dependencies တွေကို install လုပ်ဖို့အတွက် plugin ထည့်ပါ
  # ဒါမှ netlify/functions/package.json ထဲက dependencies တွေကို သိမှာပါ

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200